config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
	root 'welcome#home'
  resources :users
  resources :treatments
  resources :archives
  resources :appointments
  resources :medicines
  resources :pacients, controller: 'users', type: 'Pacient' 
	resources :secretaries, controller: 'users', type: 'Secretary' 
	resources :admins, controller: 'users', type: 'Admin'
	get 'login', to: 'login#new'
  post 'login', to: 'login#create'
  delete 'logout', to: 'login#destroy'
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :medicines

  validates :dosis, :user_id, presence: true
  
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  before_action :authenticate_user
  before_action :set_treatment, only: [:show, :edit, :update, :destroy]

  # GET /treatments
  # GET /treatments.json
  def index
    if current_user.type == "Admin"
      @treatments = Treatment.all
    else 
      @treatments = current_user.treatments
    end
  end

  # GET /treatments/1
  # GET /treatments/1.json
  def show
    @medicines = @treatment.medicines
  end

  # GET /treatments/new
  def new
    @treatment = Treatment.new
    @medicines = Medicine.all
  end

  # GET /treatments/1/edit
  def edit
    @medicines = Medicine.all
  end

  # POST /treatments
  # POST /treatments.json
  def create
    @treatment = Treatment.new(treatment_params)
    @medicines = Medicine.find(params[:treatment][:medicine_ids].drop(1))

    @treatment.medicines << @medicines
    respond_to do |format|
      if @treatment.save
        format.html { redirect_to @treatment, success: 'Treatment was successfully created.' }
        format.json { render :show, status: :created, location: @treatment }
      else
        format.html { render :new }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /treatments/1
  # PATCH/PUT /treatments/1.json
  def update
    @medicines = Medicine.find(params[:treatment][:medicine_ids].drop(1))
    if @medicines.length == @treatment.medicines.length
      @medicines = @medicines - @treatment.medicines
    else
      @treatment.medicines = @medicines
    end
    respond_to do |format|
      if @treatment.update(treatment_params)
        format.html { redirect_to @treatment, success: 'Treatment was successfully updated.' }
        format.json { render :show, status: :ok, location: @treatment }
      else
        format.html { render :edit }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treatments/1
  # DELETE /treatments/1.json
  def destroy
    @treatment.destroy
    respond_to do |format|
      format.html { redirect_to treatments_url, success: 'Treatment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_treatment
      @treatment = Treatment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def treatment_params
      params.require(:treatment).permit(:dosis, :instructions, :user_id, :medicines)
    end

    def authenticate_user
      if !current_user
        redirect_to root_url
      elsif current_user.type == "Secretary"
        redirect_to root_path, danger: "No tienes permisos para acceder a los tratamientos"
      end
    end
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/treatments/_form.html.erb
<%= form_with(model: treatment, local: true) do |form| %>
  <% if treatment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(treatment.errors.count, "error") %> prohibited this treatment from being saved:</h2>

      <ul>
      <% treatment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mt-4">
    <%= form.label :dosis %>
    <%= form.text_field :dosis, class: "form-control" %>
  </div>

  <div class="field mt-4">
    <%= form.label :instructions %>
    <%= form.text_area :instructions, class: "form-control" %>
  </div>

  <div class="field mt-4">
    <%= form.label "Paciente" %>
    <%= form.collection_select :user_id, Pacient.all, :id, :whole_name, prompt: true, class: "form-control" %>
  </div>

  <div class="field mt-4">
      <%= form.collection_check_boxes(:medicine_ids, Medicine.all, :id, :get_name) do |m| %>
        <%= m.label { m.check_box + " " + m.text} %>
      <% end %>
  </div>

  <div class="actions mt-4">
    <%= form.submit %>
  </div>
<% end %>

app/views/treatments/edit.html.erb
<h1>Editing Treatment</h1>

<%= render 'form', treatment: @treatment %>

<%= link_to 'Ver tratamiento', @treatment, class: "btn btn-outline-warning mt-3" %> |
<%= link_to 'Regresar a tratamientos', treatments_path, class: "btn btn-outline-warning mt-3" %>

app/views/treatments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Treatments</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Dosis</th>
      <th>Instrucciones</th>
      <th>Paciente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @treatments.each do |treatment| %>
      <tr>
        <td><%= treatment.dosis %></td>
        <td><%= treatment.instructions %></td>
        <td><%= treatment.user.names + " " + treatment.user.lastnames %></td>
        <td><%= link_to 'Mostar', treatment %></td>
        <% if current_user.type != "Pacient" %>
          <td><%= link_to 'Editar', edit_treatment_path(treatment) %></td>
          <td><%= link_to 'Destruir', treatment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.type != "Pacient" %>
  <%= link_to 'Nuevo Tratamiento', new_treatment_path, class: "btn btn-outline-warning mt-4" %>
<% else %>
  <p><i>
  Si tiene alguna molestia con algunos de los medicamentos, favor de mandar un mensaje al 81 82 52 58 10 o marcar al consultorio para verlo lo más pronto posible, gracias.
</i></p>
<% end %>

app/views/treatments/new.html.erb
<h1>New Treatment</h1>

<%= render 'form', treatment: @treatment %>

<%= link_to 'De vuelta a los tratamientos', treatments_path, class: "btn btn-outline-warning mt-4" %>

app/views/treatments/show.html.erb
<div class="jumbotron">
  <p id="notice"><%= notice %></p>

  <% @medicines.each do |medicine| %>
    <p>
      <% if current_user.type != "Pacient" %>
        <strong class="display-4"><%= link_to medicine.name, medicine %></strong>
      <% else %>
        <strong class="display-4"><%= medicine.name %></strong>
      <% end %>
    </p>
  <% end %>

  <p class="lead">
    <strong>Dosis:</strong>
    <%= @treatment.dosis %>
  </p>

  <p class="lead">
    <strong>Instructions:</strong>
    <%= @treatment.instructions %>
  </p>

  <p>
    <strong class="lead">Paciente:</strong>
    <%= @treatment.user.names + " " + @treatment.user.lastnames %>
  </p>
  <p>
    <% if current_user.type != "Pacient" %>
      <%= link_to 'Editar', edit_treatment_path(@treatment), class: "btn btn-outline-warning" %> |
      <%= link_to 'Volver a los tratamientos', treatments_path, class: "btn btn-outline-warning" %>
    <% else %>
      <%= link_to 'Volver a los tratamientos', treatments_path, class: "btn btn-outline-warning" %>
    <% end %>
  </p>
</div>