config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
	root 'welcome#home'
  resources :users
  resources :treatments
  resources :archives
  resources :appointments
  resources :medicines
  resources :pacients, controller: 'users', type: 'Pacient' 
	resources :secretaries, controller: 'users', type: 'Secretary' 
	resources :admins, controller: 'users', type: 'Admin'
	get 'login', to: 'login#new'
  post 'login', to: 'login#create'
  delete 'logout', to: 'login#destroy'
end

app/models/medicine.rb
class Medicine < ApplicationRecord
	has_and_belongs_to_many :treatments

	validates :name, :pills, presence: true
	validates :pills, numericality: {:greater_than_or_equal_to => 0, :less_than_or_equal_to => 40}

	def get_name
		name
	end
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_action :authenticate_user
  before_action :set_medicine, only: [:show, :edit, :update, :destroy]

  # GET /medicines
  # GET /medicines.json
  def index
    @medicines = Medicine.all
  end

  # GET /medicines/1
  # GET /medicines/1.json
  def show
  end

  # GET /medicines/new
  def new
    @medicine = Medicine.new
  end

  # GET /medicines/1/edit
  def edit
  end

  # POST /medicines
  # POST /medicines.json
  def create
    @medicine = Medicine.new(medicine_params)

    respond_to do |format|
      if @medicine.save
        format.html { redirect_to @medicine, success: 'Medicine was successfully created.' }
        format.json { render :show, status: :created, location: @medicine }
      else
        format.html { render :new }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicines/1
  # PATCH/PUT /medicines/1.json
  def update
    respond_to do |format|
      if @medicine.update(medicine_params)
        format.html { redirect_to @medicine, success: 'Medicine was successfully updated.' }
        format.json { render :show, status: :ok, location: @medicine }
      else
        format.html { render :edit }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicines/1
  # DELETE /medicines/1.json
  def destroy
    @medicine.destroy
    respond_to do |format|
      format.html { redirect_to medicines_url, success: 'Medicine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicine
      @medicine = Medicine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medicine_params
      params.require(:medicine).permit(:name, :pills, :description)
    end

    def authenticate_user
      if !current_user
        redirect_to root_url
      elsif current_user.type == "Pacient"
        redirect_to root_url, danger: 'No tienes acceso a esta información.'
      end
    end
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/views/medicines/_form.html.erb
  <%= form_with(model: medicine, local: true) do |form| %>
    <% if medicine.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(medicine.errors.count, "error") %> prohibited this medicine from being saved:</h2>

        <ul>
        <% medicine.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field mt-3">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control"%>
    </div>

    <div class="field mt-3">
      <%= form.label :pills %>
      <%= form.number_field :pills, class: "form-control" %>
    </div>

    <div class="field mt-3">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="actions mt-3">
      <%= form.submit %>
    </div>
  <% end %>

app/views/medicines/edit.html.erb
<div class="container">
	<h1>Editing Medicine</h1>

	<%= render 'form', medicine: @medicine %>

	<%= link_to 'Ver medicamento', @medicine, class: "btn btn-outline-info mt-3" %> |
	<%= link_to 'Regresar a mediciamentos', medicines_path, class: "btn btn-outline-info mt-3" %>
</div>

app/views/medicines/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Medicamentos</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Cantidad de Píldoras</th>
        <th>Descripción</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @medicines.each do |medicine| %>
        <tr>
          <td><%= medicine.name %></td>
          <td><%= medicine.pills %></td>
          <td><%= medicine.description %></td>
          <td><%= link_to 'Mostrar', medicine %></td>
          <td><%= link_to 'Editar', edit_medicine_path(medicine) %></td>
          <td><%= link_to 'Destruir', medicine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Nuevo Medicamento', new_medicine_path, class: "btn btn-outline-info" %>
</div>

app/views/medicines/new.html.erb
<div class="container mt-5">
	<h1>Nuevo Medicamento</h1>

	<%= render 'form', medicine: @medicine %>

	<%= link_to 'De vuelta a medicamentos', medicines_path, class: "btn btn-outline-info mt-3" %>	
</div>

app/views/medicines/show.html.erb
<div class="jumbotron">
	<p id="notice"><%= notice %></p>

	<p>
	  <h1 class="display-4"><%= @medicine.name %></h1>
	</p>

	<p class="lead">
	  <%= "Contiene #{@medicine.pills} píldoras" %>
	</p>

	<p class="lead">
	  <strong>Descripción:</strong>
	  <%= @medicine.description %>
	</p>

	<%= link_to 'Editar', edit_medicine_path(@medicine), class: "btn btn-outline-info" %> |
	<%= link_to 'Regresar a medicamentos', medicines_path, class: "btn btn-outline-info" %>
</div>