config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
	root 'welcome#home'
  resources :users
  resources :treatments
  resources :archives
  resources :appointments
  resources :medicines
  resources :pacients, controller: 'users', type: 'Pacient' 
	resources :secretaries, controller: 'users', type: 'Secretary' 
	resources :admins, controller: 'users', type: 'Admin'
	get 'login', to: 'login#new'
  post 'login', to: 'login#create'
  delete 'logout', to: 'login#destroy'
end

app/models/archive.rb
class Archive < ApplicationRecord
  belongs_to :user

  validates :title, :description, :document, presence: true

  mount_uploader :document, DocumentUploader
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  before_action :set_archive, only: [:show, :edit, :update, :destroy]

  # GET /archives
  # GET /archives.json
  def index
    if current_user.type == "Admin"  
      @archives = Archive.all
    else
      @archives = current_user.archives
    end
  end

  # GET /archives/1
  # GET /archives/1.json
  def show
  end

  # GET /archives/new
  def new
    @archive = Archive.new
  end

  # GET /archives/1/edit
  def edit
    
  end

  # POST /archives
  # POST /archives.json
  def create
    @archive = Archive.new(archive_params)
    respond_to do |format|
      if @archive.save
        format.html { redirect_to @archive, success: 'Archivo creado exitosamente.' }
        format.json { render :show, status: :created, location: @archive }
      else
        format.html { render :new }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /archives/1
  # PATCH/PUT /archives/1.json
  def update
    respond_to do |format|
      if @archive.update(archive_params)
        format.html { redirect_to @archive, success: 'Archivo actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @archive }
      else
        format.html { render :edit }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /archives/1
  # DELETE /archives/1.json
  def destroy
    @archive.destroy
    respond_to do |format|
      format.html { redirect_to archives_url, success: 'Archivo eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_archive
      @archive = Archive.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def archive_params
      params[:archive][:user_id] = current_user.id
      params.require(:archive).permit(:title, :description, :user_id, :document)
    end
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/views/archives/_form.html.erb
<%= form_with(model: archive, local: true) do |form| %>
  <% if archive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(archive.errors.count, "error") %> prohibited this archive from being saved:</h2>

      <ul>
      <% archive.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mt-3">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field mt-3">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="field mt-3"> 
    <%= form.label :document %>
    <%= form.file_field :document %>
  </div>

  <div class="field mt-3">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: "form-control", value: current_user.names + " " + current_user.lastnames, :disabled => true %>
  </div>

  <div class="actions mt-3">
    <%= form.submit %>
  </div>
<% end %>

app/views/archives/edit.html.erb
<h1>Editing Archive</h1>

<%= render 'form', archive: @archive %>

<%= link_to 'Ver archivo', @archive, class: "btn btn-outline-success mt-3" %> |
<%= link_to 'Regresar a archivos', archives_path, class: "btn btn-outline-success mt-3" %>

app/views/archives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Archives</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th>Document</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @archives.each do |archive| %>
      <tr>
        <td><%= archive.title %></td>
        <td><%= archive.description %></td>
        <td><%= archive.user.names + " " + archive.user.lastnames %></td>
        <td><%= archive.document.file.filename %></td>
        <td><%= link_to 'Show', archive %></td>
        <td><%= link_to 'Edit', edit_archive_path(archive) %></td>
        <td><%= link_to 'Destroy', archive, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Archive', new_archive_path, class: "btn btn-outline-success" %>

app/views/archives/new.html.erb
<h1>New Archive</h1>

<%= render 'form', archive: @archive %>

<%= link_to 'Back', archives_path, class: "btn btn-outline-success mt-4" %>

app/views/archives/show.html.erb
<div class="jumbotron">
	<p id="notice"><%= notice %></p>

	<p>
	  <h1 class="display-3"><%= @archive.title %></h1> 
	</p>

	<p class="lead">
	  <strong>Descripción:</strong>
	  <%= @archive.description %>
	</p>

	<p class="lead">
	  <strong>Usuario:</strong>
	  <%= @archive.user.names + " " + @archive.user.lastnames %>
	</p>

	<p class="lead">
		<strong>Documento:</strong>
		<%= image_tag @archive.document_url, style:'height: 225px; width: 100%; display: block;'%>
	</p>

	<p class="lead">
		<%= link_to 'Descargar archivo', @archive.document.url, class: "btn btn-outline-success" %>
	</p>

	<%= link_to 'Editar archivo', edit_archive_path(@archive), class: "btn btn-outline-success" %> |
	<%= link_to 'Regresar a archivos', archives_path, class: "btn btn-outline-success" %>
</div>