config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
	root 'welcome#home'
  resources :users
  resources :treatments
  resources :archives
  resources :appointments
  resources :medicines
  resources :pacients, controller: 'users', type: 'Pacient' 
	resources :secretaries, controller: 'users', type: 'Secretary' 
	resources :admins, controller: 'users', type: 'Admin'
	get 'login', to: 'login#new'
  post 'login', to: 'login#create'
  delete 'logout', to: 'login#destroy'
end

app/models/admin.rb
class Admin < User

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  validates :title, :appointment_date, :user_id, presence: true
end

app/models/archive.rb
class Archive < ApplicationRecord
  belongs_to :user

  validates :title, :description, :document, presence: true

  mount_uploader :document, DocumentUploader
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :users
end

app/models/medicine.rb
class Medicine < ApplicationRecord
	has_and_belongs_to_many :treatments

	validates :name, :pills, presence: true
	validates :pills, numericality: {:greater_than_or_equal_to => 0, :less_than_or_equal_to => 40}

	def get_name
		name
	end
end

app/models/pacient.rb
class Pacient < User
	validates :category_id, presence: true
	validates :init_preg_week, presence: true, if: :is_pregnant?
	validates :init_preg_week, numericality: { only_integer: true, :greater_than_or_equal_to => 0, :less_than_or_equal_to => 40}

	def is_pregnant?
		category_id == 1
	end

	def whole_name
		"#{names} #{lastnames}"
	end
end

app/models/secretary.rb
class Secretary < User
	validates :salary, presence: true
	validates :salary, numericality: {:greater_than_or_equal_to => 0, :less_than_or_equal_to => 10000}
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :medicines

  validates :dosis, :user_id, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
	 before_save { self.email = email.downcase }
	 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	belongs_to :category
    has_many :treatments
    has_many :archives
    has_many :appointments
  	validates :names, :lastnames, :age, :cellphone, :type, presence: true
  	validates :email, presence: true, length:{ maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false } 

  	has_secure_password
  	validates :password, presence: true, length: { minimum: 6 }
  	def self.types 
	 	 %w(Pacient Secretary Admin)
	 end

   def whole_name
    "#{names} #{lastnames}"
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new
    if current_user
      redirect_to root_path
      flash.now[:danger] = "Ya inicio sesión"
    end
  end

  def create
  	@user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in @user
      redirect_to root_path
    else
      redirect_to login_path, danger: "El correo/contraseña son inválidos"
    end
  end

  def destroy
  	log_out
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
    	session[:user_id] = user.id
  	end

  	def log_out
    	session.delete(:user_id)
    	@current_user = nil
  	end

  	def current_user
	    if session[:user_id]
	      @current_user ||= User.find_by(id: session[:user_id])
	    end
	end
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def sti_user_path(type = "user", user = nil, action = nil)
  		send "#{format_sti(action, type, user)}_path", user
	end

	def format_sti(action, type, user)
	  action || user ? "#{format_action(action)}#{type.underscore}" : "#{type.underscore.pluralize}"
	end

	def format_action(action)
	  action ? "#{action}_" : ""
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!--
Admin account:
  email: crdluis97@gmail.com
  passw: qwerty

  email: guiga@itesm.mx
  passw: chavoruco

Secretary account:
  email: sofy.rady@google.com
  passw: hermana

Pacient account:
  email: asmg96@hotmail.com
  passw: hermosa
  ( Puse hermosa porque es mi novia y no se me ocurrió otro password, no soy tan mandilón, lo juro )
-->

<!DOCTYPE html>
<html>
  <head>
    <title>Dra. Martha Colunga</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light ">
        <% if current_user %>
          <a class="navbar-brand" href="/">Bienvenido <%= current_user.names + " " + current_user.lastnames%></a>
        <% else %>
          <a class="navbar-brand" href="/">Doctora Martha Colunga</a>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <% if current_user %>
          <% if current_user.type != "Pacient" %>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <%= link_to 'Medicamentos', medicines_path, class: "nav-link mx-4" %>
                </li>
                <% if current_user.type != "Secretary" %>
                  <li class="nav-item">
                    <%= link_to 'Tratamientos', treatments_path, class: "nav-link mx-4" %>
                  </li>
                <% end %>
                <li class="nav-item">
                  <%= link_to 'Citas', appointments_path, class: "nav-link mx-4" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Archivos', archives_path, class: "nav-link mx-4" %>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle mx-4" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Usuarios
                  </a>              
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <% if current_user.type == "Secretary" %>
                    <%= link_to 'Pacientes', sti_user_path("pacients"), class: "dropdown-item" %>
                  <% else %>
                    <%= link_to 'Todos los usuarios', sti_user_path("users"), class: "dropdown-item" %>
                    <%= link_to 'Pacientes', sti_user_path("pacients"), class: "dropdown-item" %>
                    <%= link_to 'Secretarias', sti_user_path("secretaries"), class: "dropdown-item" %>
                    <%= link_to 'Administradores', sti_user_path("admins"), class: "dropdown-item" %>
                  <% end %>
                  </div>
                </li>
              </ul>
            </div>
          <% elsif current_user %>
              <ul class="navbar-nav">
                <li class="nav-item">
                  <%= link_to 'Archivos', archives_path, class: "nav-link mx-4" %>            
                </li>
                <li class="nav-item">
                  <%= link_to 'Tratamientos', treatments_path, class: "nav-link mx-4" %>            
                </li>
                <li class="nav-item">
                  <%= link_to 'Citas', appointments_path, class: "nav-link mx-4" %>            
                </li>
              </ul>
          <% end %>      
        <% end %>
        <% if !current_user %>
          <% if current_page?(root_url) %>
            <%= link_to 'Iniciar Sesión', login_path, class: "btn btn-outline-success mx-5" %>
          <% else %>
            <%= link_to 'Volver a página principal', root_path, class: "btn btn-outline-warning mx-5" %>
          <% end %>
        <% else %>
          <%= link_to 'Terminar Sesión', logout_path, method: :delete, class: "btn btn-outline-danger mx-5" %>
        <% end %>
      </nav>
    </header>
    <div class="container mt-5">
      <% flash.each do |name, msg| %>
        <div class='alert alert-<%=name%> alert-dismissible fade show'>
          <%= msg %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <%= yield %>
    </div>     

  </body>
</html>